export type Publication = {
  id: string;
  year: number;
  title: string;
  authors: string;
  venue: string;
  ranking?: string[];
  badge?: string;
  venueImage?: string;
  doi?: string;
  image?: string;
  pdf?: string;
  code?: string;
  project?: string;
  video?: string;
  featured?: boolean;
  representative?: boolean;
};

// 仅收录 CCF 推荐目录 C 类及以上论文；等级依据中国计算机学会官网分领域目录核对。
export const publications: Publication[] = [
  // ---------- 2025 ----------
  {
    id: "weighted-poisson-2025",
    year: 2025,
    title: "Weighted Poisson-disk Resampling on Large-Scale Point Clouds",
    authors: "Xianhe Jiao, Chenlei Lv, Junli Zhao, Ran Yi, Yu-Hui Wen, Zhenkuan Pan, Zhongke Wu, Yong-Jin Liu",
    venue: "Proceedings of the AAAI Conference on Artificial Intelligence, 39(4): 4084–4092",
    ranking: ["CCF A"],
    badge: "AAAI 2025",
    venueImage: "/images/venues/aaai.jpg",
    image: "/images/publications/weighted-poisson.jpg",
    pdf: "https://arxiv.org/pdf/2412.09177",
    code: "https://github.com/vvvwo/Weighted-Poisson-disk-Resampling",
    doi: "https://doi.org/10.1609/aaai.v39i4.32428",
    featured: true,
    representative: true,
  },
  {
    id: "skull-to-face-2025",
    year: 2025,
    title: "Skull-to-Face: Anatomy-Guided 3D Facial Reconstruction and Editing",
    authors: "Yongqing Liang, Congyi Zhang, Junli Zhao, Wenping Wang, Xin Li",
    venue: "IEEE Transactions on Visualization and Computer Graphics, 31(9): 6425–6436",
    ranking: ["CCF A", "SCI 1区"],
    badge: "IEEE TVCG",
    image: "/images/publications/skull-to-face.jpg",
    pdf: "https://arxiv.org/pdf/2403.16207",
    code: "https://github.com/xmlyqing00/skull-to-face",
    project: "https://xmlyqing00.github.io/skull-to-face-page/",
    video: "https://xmlyqing00.github.io/skull-to-face-page/#demo-videos",
    doi: "https://doi.org/10.1109/TVCG.2024.3515093",
    featured: true,
    representative: true,
  },
  {
    id: "gausurfaceavatar-2025",
    year: 2025,
    title: "GauSurfaceAvatar: A Realistic Human Head Model with Variable Texture Based on 2D Gaussians",
    authors: "Lijie Geng, Junli Zhao, Lin Gao, Ran Yi, Fuqing Duan, Zhenkuan Pan, Yong-Jin Liu",
    venue: "IEEE International Conference on Multimedia and Expo (ICME) 2025: 1–6",
    ranking: ["CCF B"],
    badge: "ICME 2025",
    image: "/images/publications/gausurfaceavatar.jpg",
    doi: "https://doi.org/10.1109/ICME59968.2025.11209075",
    representative: true,
  },
  {
    id: "mmae-2025",
    year: 2025,
    title: "MMAE: A Universal Image Fusion Method via Mask Attention Mechanism",
    authors: "Xiangxiang Wang, Lixing Fang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Pattern Recognition, 158: 111041",
    ranking: ["CCF B", "SCI 1区"],
    badge: "Pattern Recognition",
    image: "/images/publications/mmae.jpg",
    doi: "https://doi.org/10.1016/j.patcog.2024.111041",
    code: "https://github.com/xiangxiang-wang/MMAE",
    representative: true,
  },
  {
    id: "sketch123-2025",
    year: 2025,
    title: "Sketch123: Multi-spectral Channel Cross Attention for Sketch-based 3D Generation via Diffusion Models",
    authors: "Zhentong Xu, Long Zeng, Junli Zhao, Baodong Wang, Zhenkuan Pan, Yong-Jin Liu",
    venue: "Computer-Aided Design, 185: 103896",
    ranking: ["CCF B"],
    badge: "Computer-Aided Design",
    doi: "https://doi.org/10.1016/j.cad.2025.103896",
  },
  {
    id: "craniofacial-superimposition-2025",
    year: 2025,
    title: "Geometric Feature-Driven Metric Learning for 3D Craniofacial Superimposition",
    authors: "Qingdong Long, Junli Zhao, Fuqing Duan, Chengyuan Wang, Xuesong Wang, Lijie Geng, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE ICASSP 2025: 1–5",
    ranking: ["CCF B"],
    badge: "ICASSP 2025",
    doi: "https://doi.org/10.1109/ICASSP49660.2025.10890007",
  },
  {
    id: "freehand-sketch-elastic-2025",
    year: 2025,
    title: "Freehand Sketch-Based 3D Reconstruction with Contour Constraints via Elastic Metrics",
    authors: "Gaoyang Liu, Chunyang Huo, Zhentong Xu, Junli Zhao, Yishan Dong, Baodong Wang",
    venue: "Proceedings of the 31st ACM Symposium on Virtual Reality Software and Technology (VRST 2025)",
    ranking: ["CCF C"],
    badge: "VRST 2025",
    doi: "https://doi.org/10.1145/3756884.3766043",
  },
  // ---------- 2024 ----------
  {
    id: "msl-net-2024",
    year: 2024,
    title: "MSL-Net: Sharp Feature Detection Network for 3D Point Clouds",
    authors: "Xianhe Jiao, Chenlei Lv, Ran Yi, Junli Zhao, Zhenkuan Pan, Zhongke Wu, Yong-Jin Liu",
    venue: "IEEE Transactions on Visualization and Computer Graphics, 30(9): 6433–6446",
    ranking: ["CCF A", "SCI 1区"],
    badge: "IEEE TVCG",
    image: "/images/publications/msl-net.jpg",
    pdf: "https://aliexken.github.io/papers/2023_MSL-Net.pdf",
    code: "https://github.com/XianheJiao/Sharp-feature-detection-in-point-cloud-",
    doi: "https://doi.org/10.1109/TVCG.2023.3346907",
    featured: true,
    representative: true,
  },
  {
    id: "siamese-cycle-2024",
    year: 2024,
    title: "Intrinsic Morphological Relationship Guided 3D Craniofacial Reconstruction Using Siamese Cycle Attention GAN",
    authors: "Junli Zhao, Chengyuan Wang, Yu-Hui Wen, Fuqing Duan, Ran Yi, Yong-Jin Liu, Qingdong Long, Zhenkuan Pan, Xianfeng Gu",
    venue: "SIGGRAPH Asia 2024 Technical Communications",
    ranking: ["CCF A"],
    badge: "SIGGRAPH Asia 2024",
    image: "/images/publications/siamese-gan.jpg",
    doi: "https://doi.org/10.1145/3681758.3698016",
    featured: true,
    representative: true,
  },
  {
    id: "mfdan-2024",
    year: 2024,
    title: "MFDAN: Multi-level Flow-Driven Attention Network for Micro-Expression Recognition",
    authors: "Wenhao Cai, Junli Zhao, Ran Yi, Minjing Yu, Fuqing Duan, Zhenkuan Pan, Yong-Jin Liu",
    venue: "IEEE Transactions on Circuits and Systems for Video Technology, 34(12): 12823–12836",
    ranking: ["CCF B", "SCI 1区"],
    badge: "IEEE TCSVT",
    image: "/images/publications/mfdan.jpg",
    doi: "https://doi.org/10.1109/TCSVT.2024.3437481",
    representative: true,
  },
  {
    id: "unsupervised-multifocus-2024",
    year: 2024,
    title: "An unsupervised multi-focus image fusion method via dual-channel convolutional network and discriminator",
    authors: "Lixing Fang, Xiangxiang Wang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Computer Vision and Image Understanding, 244: 104029",
    ranking: ["CCF B"],
    badge: "CVIU",
    doi: "https://doi.org/10.1016/j.cviu.2024.104029",
  },
  {
    id: "skeletonformer-2024",
    year: 2024,
    title: "SkeletonFormer: Point Cloud Completion with Dynamic Selective Skeleton Points",
    authors: "Beiqi Liu, Fuqing Duan, Junli Zhao",
    venue: "ICMR 2024: 897–905",
    ranking: ["CCF B"],
    badge: "ICMR 2024",
    doi: "https://doi.org/10.1145/3652583.3658022",
  },
  {
    id: "uud-fusion-2024",
    year: 2024,
    title: "UUD-Fusion: An Unsupervised Universal Image Fusion Approach via Generative Diffusion Model",
    authors: "Xiangxiang Wang, Lixing Fang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Computer Vision and Image Understanding, 249: 104218",
    ranking: ["CCF B"],
    badge: "CVIU",
  },
  {
    id: "mattrans-2024",
    year: 2024,
    title: "MatTrans: Material Reflectance Property Estimation of Complex Objects with Transformer",
    authors: "Liping Wu, Bin Cheng, Wentao Chao, Junli Zhao, Fuqing Duan",
    venue: "CVM 2024: 197–217",
    ranking: ["CCF C"],
    badge: "CVM 2024",
    doi: "https://doi.org/10.1007/978-981-97-2095-8_11",
  },
  {
    id: "identity-preserving-2024",
    year: 2024,
    title: "Identity-preserving 3D Facial Completion under Skull Constraints",
    authors: "Longtao Yu, Junli Zhao, Fuqing Duan, Chenlei Lv, Dantong Li, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE International Joint Conference on Biometrics (IJCB): 1–10",
    ranking: ["CCF C"],
    badge: "IJCB 2024",
    doi: "https://doi.org/10.1109/IJCB62174.2024.10744459",
  },
  {
    id: "skull-gender-2024",
    year: 2024,
    title: "Morphology-Guided 3D Skull Gender Identification with Point-BERT",
    authors: "Baodong Wang, Shuo Wang, Junli Zhao, Tongyan Liu, Zhi Wang, Zhenkuan Pan, Mingquan Zhou",
    venue: "ICONIP 2024, Communications in Computer and Information Science 2296",
    ranking: ["CCF C"],
    badge: "ICONIP 2024",
    doi: "https://doi.org/10.1007/978-981-96-7033-8_20",
  },
  {
    id: "pottsnn-2024",
    year: 2024,
    title: "PottsNN: A Variational Neural Network Based on Potts Model for Image Segmentation",
    authors: "Reyan Wang, Zhenghong Zhong, Junli Zhao, Shaoqing Gong, Zhenkuan Pan, Weibo Wei",
    venue: "PRCV 2024: 142–156",
    ranking: ["CCF C"],
    badge: "PRCV 2024",
  },
  // ---------- 2023 ----------
  {
    id: "craniofacial-landmarks-2023",
    year: 2023,
    title: "Robust 3D Craniofacial Landmarks Localization by An End-to-End Regression Network",
    authors: "Xianhe Jiao, Junli Zhao, Chenlei Lv, Fuqing Duan, Zhenkuan Pan, Xin Li",
    venue: "IEEE ICME 2023: 900–905",
    ranking: ["CCF B"],
    badge: "ICME 2023",
    doi: "https://doi.org/10.1109/ICME55011.2023.00159",
  },
  {
    id: "4d-facial-survey-2023",
    year: 2023,
    title: "4D Facial Analysis: A Survey of Datasets, Algorithms and Applications",
    authors: "Yong-Jin Liu, Baodong Wang, Lin Gao, Junli Zhao, Ran Yi, Minjing Yu, Zhenkuan Pan, Xianfeng Gu",
    venue: "Computers & Graphics, 115: 423–445",
    ranking: ["CCF C"],
    badge: "Computers & Graphics",
    doi: "https://doi.org/10.1016/j.cag.2023.07.014",
  },
  {
    id: "cr-net-2023",
    year: 2023,
    title: "CR-Net: A Robust Craniofacial Registration Network by Introducing Wasserstein Distance Constraint and Geometric Attention Mechanism",
    authors: "Zhenyu Dai, Junli Zhao, Xiaodan Deng, Fuqing Duan, Dantong Li, Zhenkuan Pan, Mingquan Zhou",
    venue: "Computers & Graphics, 116: 194–205",
    ranking: ["CCF C"],
    badge: "Computers & Graphics",
    doi: "https://doi.org/10.1016/j.cag.2023.08.015",
  },
  // ---------- 2022 ----------
  {
    id: "depth-map-craniofacial-2022",
    year: 2022,
    title: "An End-to-End Conditional Generative Adversarial Network Based on Depth Map for 3D Craniofacial Reconstruction",
    authors: "Niankai Zhang, Junli Zhao, Fuqing Duan, Zhenkuan Pan, Zhongke Wu, Mingquan Zhou, Xianfeng Gu",
    venue: "30th ACM International Conference on Multimedia: 759–768",
    ranking: ["CCF A"],
    badge: "ACM MM 2022",
    image: "/images/publications/acm-mm-depth-map.jpg",
    doi: "https://doi.org/10.1145/3503161.3548254",
    featured: true,
    representative: true,
  },
  // ---------- 2021 ----------
  {
    id: "hf-ggr-2021",
    year: 2021,
    title: "Craniofacial Reconstruction Based on Heat Flow Geodesic Grid Regression (HF-GGR) Model",
    authors: "Bin Jia, Junli Zhao, Shiqing Xin, Fuqing Duan, Zhenkuan Pan, Zhongke Wu, Jinhua Li, Mingquan Zhou",
    venue: "Computers & Graphics, 97: 258–267",
    ranking: ["CCF C"],
    badge: "Computers & Graphics",
    doi: "https://doi.org/10.1016/j.cag.2021.04.029",
  },
  // ---------- 2019 ----------
  {
    id: "skull-registration-2019",
    year: 2019,
    title: "Automatic and Robust Skull Registration Based on Discrete Uniformization",
    authors: "Junli Zhao, Xin Qi, Chengfeng Wen, Na Lei, Xianfeng Gu",
    venue: "IEEE/CVF International Conference on Computer Vision (ICCV): 431–440",
    ranking: ["CCF A"],
    badge: "ICCV 2019",
    image: "/images/publications/iccv-skull-registration.jpg",
    pdf: "https://openaccess.thecvf.com/content_ICCV_2019/papers/Zhao_Automatic_and_Robust_Skull_Registration_Based_on_Discrete_Uniformization_ICCV_2019_paper.pdf",
    doi: "https://doi.org/10.1109/ICCV.2019.00052",
    featured: true,
    representative: true,
  },
  {
    id: "mtap-fusion-2019",
    year: 2019,
    title: "Improving performance of medical image fusion using histogram, dictionary learning and sparse representation",
    authors: "Yi Li, Zhihan Lv, Junli Zhao, Zhenkuan Pan",
    venue: "Multimedia Tools and Applications",
    ranking: ["CCF C"],
    badge: "MTAP",
    doi: "https://doi.org/10.1007/s11042-019-08027-9",
  },
  {
    id: "radial-curves-2019",
    year: 2019,
    title: "Automatic Craniofacial Registration Based on Radial Curves",
    authors: "Ruikun Huang, Junli Zhao, Fuqing Duan, Xin Li, Celong Liu, Xiaodan Deng, Zhenkuan Pan, Zhongke Wu, Mingquan Zhou",
    venue: "Computers & Graphics, 82: 264–274",
    ranking: ["CCF C"],
    badge: "Computers & Graphics",
    doi: "https://doi.org/10.1016/j.cag.2019.05.026",
  },
  // ---------- 2018 ----------
  {
    id: "frechet-geodesics-2018",
    year: 2018,
    title: "3D Face Similarity Measure by Fréchet Distances of Geodesics",
    authors: "Junli Zhao, Zhong-Ke Wu, Zhenkuan Pan, Fu-Qing Duan, Jin-Hua Li, Zhi-Han Lv, Kang Wang, Yu-Cong Chen",
    venue: "Journal of Computer Science and Technology, 33(1): 207–222",
    ranking: ["CCF B"],
    badge: "JCST",
    doi: "https://doi.org/10.1007/s11390-018-1814-7",
  },
  // ---------- 2014 ----------
  {
    id: "diffusion-distance-2014",
    year: 2014,
    title: "A Scale-Invariant Diffusion Distance for Non-rigid Shape Analysis",
    authors: "Kang Wang, Zhongke Wu, Taorui Jia, Sajid Ali, Junli Zhao, Guoliang Yang, Mingquan Zhou",
    venue: "2014 International Conference on Virtual Reality and Visualization (ICVRV)",
    ranking: ["CCF C"],
    badge: "ICVRV 2014",
    doi: "https://doi.org/10.1109/ICVRV.2014.63",
  },
];

export const publicationSummary = {
  total: publications.length,
  ccfA: publications.filter((item) => item.ranking?.includes("CCF A")).length,
  ccfB: publications.filter((item) => item.ranking?.includes("CCF B")).length,
  ccfC: publications.filter((item) => item.ranking?.includes("CCF C")).length,
  note: "仅展示 CCF 推荐目录 C 类及以上论文，按年份排列，同年内按 CCF A → B → C 排序；等级依据中国计算机学会官网分领域目录核对。",
};

export const featuredPublications = publications.filter((item) => item.featured);

export const representativePublications = publications.filter((item) => item.representative);
