export type Publication = {
  id: string;
  year: number;
  title: string;
  authors: string;
  venue: string;
  ranking?: string[];
  badge?: string;
  doi?: string;
  image?: string;
  pdf?: string;
  code?: string;
  project?: string;
  video?: string;
  featured?: boolean;
  representative?: boolean;
};

export const publications: Publication[] = [
  {
    id: "omnisketch-2026",
    year: 2026,
    title: "OmniSketch: Sketch-Guided Text-to-3D Generation With High-Fidelity Geometry and Texture",
    authors: "Xinbin Sun, Zhentong Xu, Guodong Wang, Fuqing Duan, Junli Zhao, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE Computer Graphics and Applications, 46(3): 68–81",
    doi: "https://doi.org/10.1109/MCG.2026.3667017",
    featured: true,
  },
  {
    id: "weighted-poisson-2025",
    year: 2025,
    title: "Weighted Poisson-disk Resampling on Large-Scale Point Clouds",
    authors: "Xianhe Jiao, Chenlei Lv, Junli Zhao, Ran Yi, Yu-Hui Wen, Zhenkuan Pan, Zhongke Wu, Yong-Jin Liu",
    venue: "Proceedings of the AAAI Conference on Artificial Intelligence, 39(4): 4084–4092",
    ranking: ["CCF A"],
    badge: "AAAI 2025",
    image: "/images/publications/weighted-poisson.jpg",
    pdf: "https://arxiv.org/pdf/2412.09177",
    code: "https://github.com/vvvwo/Weighted-Poisson-disk-Resampling",
    doi: "https://doi.org/10.1609/aaai.v39i4.32428",
    featured: true,
    representative: true,
  },
  {
    id: "skull-to-face-2025",
    year: 2025,
    title: "Skull-to-Face: Anatomy-Guided 3D Facial Reconstruction and Editing",
    authors: "Yongqing Liang, Congyi Zhang, Junli Zhao, Wenping Wang, Xin Li",
    venue: "IEEE Transactions on Visualization and Computer Graphics, 31(9): 6425–6436",
    ranking: ["SCI 1区", "CCF A"],
    badge: "IEEE TVCG",
    image: "/images/publications/skull-to-face.jpg",
    pdf: "https://arxiv.org/pdf/2403.16207",
    code: "https://github.com/xmlyqing00/skull-to-face",
    project: "https://xmlyqing00.github.io/skull-to-face-page/",
    video: "https://xmlyqing00.github.io/skull-to-face-page/#demo-videos",
    doi: "https://doi.org/10.1109/TVCG.2024.3515093",
    featured: true,
    representative: true,
  },
  {
    id: "gausurfaceavatar-2025",
    year: 2025,
    title: "GauSurfaceAvatar: A Realistic Human Head Model with Variable Texture Based on 2D Gaussians",
    authors: "Lijie Geng, Junli Zhao, Lin Gao, Ran Yi, Fuqing Duan, Zhenkuan Pan, Yong-Jin Liu",
    venue: "IEEE International Conference on Multimedia and Expo (ICME) 2025: 1–6",
    ranking: ["CCF B"],
    badge: "ICME 2025",
    image: "/images/publications/gausurfaceavatar.jpg",
    doi: "https://doi.org/10.1109/ICME59968.2025.11209075",
    representative: true,
  },
  {
    id: "mmae-2025",
    year: 2025,
    title: "MMAE: A Universal Image Fusion Method via Mask Attention Mechanism",
    authors: "Xiangxiang Wang, Lixing Fang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Pattern Recognition, 158: 111041",
    ranking: ["SCI 1区", "CCF B"],
    badge: "Pattern Recognition",
    doi: "https://doi.org/10.1016/j.patcog.2024.111041",
    code: "https://github.com/xiangxiang-wang/MMAE",
    representative: true,
  },
  {
    id: "freehand-sketch-elastic-2025",
    year: 2025,
    title: "Freehand Sketch-Based 3D Reconstruction with Contour Constraints via Elastic Metrics",
    authors: "Gaoyang Liu, Chunyang Huo, Zhentong Xu, Junli Zhao, Yishan Dong, Baodong Wang",
    venue: "Proceedings of the 31st ACM Symposium on Virtual Reality Software and Technology (VRST 2025)",
    doi: "https://doi.org/10.1145/3756884.3766043",
  },
  {
    id: "sketch123-2025",
    year: 2025,
    title: "Sketch123: Multi-spectral Channel Cross Attention for Sketch-based 3D Generation via Diffusion Models",
    authors: "Zhentong Xu, Long Zeng, Junli Zhao, Baodong Wang, Zhenkuan Pan, Yong-Jin Liu",
    venue: "Computer-Aided Design, 185: 103896",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1016/j.cad.2025.103896",
  },
  {
    id: "craniofacial-superimposition-2025",
    year: 2025,
    title: "Geometric Feature-Driven Metric Learning for 3D Craniofacial Superimposition",
    authors: "Qingdong Long, Junli Zhao, Fuqing Duan, Chengyuan Wang, Xuesong Wang, Lijie Geng, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE ICASSP 2025: 1–5",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1109/ICASSP49660.2025.10890007",
  },
  {
    id: "4dm-lddm-2025",
    year: 2025,
    title: "4DM-LDDM: A Mesh Latent Diffusion Deformable Model for 4D Facial Generation",
    authors: "Baodong Wang, Zhen Wang, Junli Zhao, Zhenkuan Pan",
    venue: "IEEE Access, 13: 183534–183548",
    doi: "https://doi.org/10.1109/ACCESS.2025.3625413",
  },
  {
    id: "vitau-2025",
    year: 2025,
    title: "ViTAU：基于 Vision Transformer 和面部动作单元的面瘫识别与分析",
    authors: "高嘉, 蔡文浩, 赵俊莉, 段福庆",
    venue: "工程科学学报, 47(2): 351–363",
    doi: "https://doi.org/10.13374/j.issn2095-9389.2024.05.06.003",
  },
  {
    id: "cranial-open-surface-2025",
    year: 2025,
    title: "Model-Guided 3D Cranial Open Surface Reconstruction Based on Euler's Elastica and Optimal Transport",
    authors: "Lijun Zhu, Junli Zhao, Pengbo Zhou, Guodong Wang, Huiqin Niu, Zhenkuan Pan",
    venue: "ICXR 2025: 116–132",
  },
  {
    id: "cpess-2025",
    year: 2025,
    title: "CPESS: Lightweight Hemiplegia Recognition Based on Video Pose Estimation and Sparse Spatiotemporal Graph Convolutional Networks",
    authors: "Yaoliang Wang, Xuesong Wang, Chong Chen, Xin He, Baodong Wang, Junli Zhao, Jianjun Sun, Lei Peng, Shuzhe Yang, Qiang Jian",
    venue: "ICXR 2025: 442–453",
  },
  {
    id: "msl-net-2024",
    year: 2024,
    title: "MSL-Net: Sharp Feature Detection Network for 3D Point Clouds",
    authors: "Xianhe Jiao, Chenlei Lv, Ran Yi, Junli Zhao, Zhenkuan Pan, Zhongke Wu, Yong-Jin Liu",
    venue: "IEEE Transactions on Visualization and Computer Graphics, 30(9): 6433–6446",
    ranking: ["SCI 1区", "CCF A"],
    badge: "IEEE TVCG",
    image: "/images/publications/msl-net.jpg",
    pdf: "https://aliexken.github.io/papers/2023_MSL-Net.pdf",
    code: "https://github.com/XianheJiao/Sharp-feature-detection-in-point-cloud-",
    doi: "https://doi.org/10.1109/TVCG.2023.3346907",
    featured: true,
    representative: true,
  },
  {
    id: "mfdan-2024",
    year: 2024,
    title: "MFDAN: Multi-level Flow-Driven Attention Network for Micro-Expression Recognition",
    authors: "Wenhao Cai, Junli Zhao, Ran Yi, Minjing Yu, Fuqing Duan, Zhenkuan Pan, Yong-Jin Liu",
    venue: "IEEE Transactions on Circuits and Systems for Video Technology, 34(12): 12823–12836",
    ranking: ["SCI 1区", "CCF B"],
    badge: "IEEE TCSVT",
    image: "/images/publications/mfdan.jpg",
    doi: "https://doi.org/10.1109/TCSVT.2024.3437481",
    representative: true,
  },
  {
    id: "siamese-cycle-2024",
    year: 2024,
    title: "Intrinsic Morphological Relationship Guided 3D Craniofacial Reconstruction Using Siamese Cycle Attention GAN",
    authors: "Junli Zhao, Chengyuan Wang, Yu-Hui Wen, Fuqing Duan, Ran Yi, Yong-Jin Liu, Qingdong Long, Zhenkuan Pan, Xianfeng Gu",
    venue: "SIGGRAPH Asia 2024 Technical Communications",
    ranking: ["SIGGRAPH Asia"],
    badge: "SIGGRAPH Asia 2024",
    image: "/images/publications/siamese-gan.jpg",
    doi: "https://doi.org/10.1145/3681758.3698016",
    featured: true,
    representative: true,
  },
  {
    id: "unsupervised-multifocus-2024",
    year: 2024,
    title: "An unsupervised multi-focus image fusion method via dual-channel convolutional network and discriminator",
    authors: "Lixing Fang, Xiangxiang Wang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Computer Vision and Image Understanding, 244: 104029",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1016/j.cviu.2024.104029",
  },
  {
    id: "blind-deblurring-2024",
    year: 2024,
    title: "A Variational Neural Network Based on Algorithm Unfolding for Image Blind Deblurring",
    authors: "Shaoqing Gong, Yeran Wang, Guangyu Yang, Weibo Wei, Junli Zhao, Zhenkuan Pan",
    venue: "Applied Sciences, 14(24): 11742",
    doi: "https://doi.org/10.3390/app142411742",
  },
  {
    id: "adaface-reconstruction-2024",
    year: 2024,
    title: "基于AdaFace优化的两阶段三维人脸精细重建方法",
    authors: "马飞, 张娟, 赵俊莉",
    venue: "青岛大学学报(自然科学版), 37(3): 40–48",
    doi: "https://doi.org/10.3969/j.issn.1006-1037.2024.03.07",
  },
  {
    id: "skeletonformer-2024",
    year: 2024,
    title: "SkeletonFormer: Point Cloud Completion with Dynamic Selective Skeleton Points",
    authors: "Beiqi Liu, Fuqing Duan, Junli Zhao",
    venue: "ICMR 2024: 897–905",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1145/3652583.3658022",
  },
  {
    id: "uud-fusion-2024",
    year: 2024,
    title: "UUD-Fusion: An Unsupervised Universal Image Fusion Approach via Generative Diffusion Model",
    authors: "Xiangxiang Wang, Lixing Fang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Computer Vision and Image Understanding, 249: 104218",
    ranking: ["CCF B"],
  },
  {
    id: "mattrans-2024",
    year: 2024,
    title: "MatTrans: Material Reflectance Property Estimation of Complex Objects with Transformer",
    authors: "Liping Wu, Bin Cheng, Wentao Chao, Junli Zhao, Fuqing Duan",
    venue: "CVM 2024: 197–217",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1007/978-981-97-2095-8_11",
  },
  {
    id: "identity-preserving-2024",
    year: 2024,
    title: "Identity-preserving 3D Facial Completion under Skull Constraints",
    authors: "Longtao Yu, Junli Zhao, Fuqing Duan, Chenlei Lv, Dantong Li, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE International Joint Conference on Biometrics (IJCB): 1–10",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1109/IJCB62174.2024.10744459",
  },
  {
    id: "skull-gender-2024",
    year: 2024,
    title: "Morphology-Guided 3D Skull Gender Identification with Point-BERT",
    authors: "Baodong Wang, Shuo Wang, Junli Zhao, Tongyan Liu, Zhi Wang, Zhenkuan Pan, Mingquan Zhou",
    venue: "ICONIP 2024, Communications in Computer and Information Science 2296",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1007/978-981-96-7033-8_20",
  },
  {
    id: "pottsnn-2024",
    year: 2024,
    title: "PottsNN: A Variational Neural Network Based on Potts Model for Image Segmentation",
    authors: "Reyan Wang, Zhenghong Zhong, Junli Zhao, Shaoqing Gong, Zhenkuan Pan, Weibo Wei",
    venue: "PRCV 2024: 142–156",
    ranking: ["CCF C"],
  },
  {
    id: "spct-2023",
    year: 2023,
    title: "Craniofacial Similarity Evaluation Based on SPCT Network",
    authors: "Yanxin Li, Junli Zhao, Weiwei Li, Jieying Tang, Zhenkuan Pan, Mingquan Zhou",
    venue: "2023 International Conference on Computer, Internet of Things and Smart City (CIoTSC): 120–125",
    doi: "https://doi.org/10.1109/CIoTSC60428.2023.00026",
  },
  {
    id: "smoothing-activation-2023",
    year: 2023,
    title: "Smoothing Piecewise Linear Activation Functions Based on Mollified Square Root Functions",
    authors: "Tony Yuxiang Pan, Guangyu Yang, Junli Zhao, Jieyu Ding",
    venue: "Mathematical Foundations of Computing, 2023",
    doi: "https://doi.org/10.3934/mfc.2023032",
  },
  {
    id: "craniofacial-landmarks-2023",
    year: 2023,
    title: "Robust 3D Craniofacial Landmarks Localization by An End-to-End Regression Network",
    authors: "Xianhe Jiao, Junli Zhao, Chenlei Lv, Fuqing Duan, Zhenkuan Pan, Xin Li",
    venue: "IEEE ICME 2023: 900–905",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1109/ICME55011.2023.00159",
  },
  {
    id: "4d-facial-survey-2023",
    year: 2023,
    title: "4D Facial Analysis: A Survey of Datasets, Algorithms and Applications",
    authors: "Yong-Jin Liu, Baodong Wang, Lin Gao, Junli Zhao, Ran Yi, Minjing Yu, Zhenkuan Pan, Xianfeng Gu",
    venue: "Computers & Graphics, 115: 423–445",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1016/j.cag.2023.07.014",
  },
  {
    id: "cr-net-2023",
    year: 2023,
    title: "CR-Net: A Robust Craniofacial Registration Network by Introducing Wasserstein Distance Constraint and Geometric Attention Mechanism",
    authors: "Zhenyu Dai, Junli Zhao, Xiaodan Deng, Fuqing Duan, Dantong Li, Zhenkuan Pan, Mingquan Zhou",
    venue: "Computers & Graphics, 116: 194–205",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1016/j.cag.2023.08.015",
  },
  {
    id: "depth-map-craniofacial-2022",
    year: 2022,
    title: "An End-to-End Conditional Generative Adversarial Network Based on Depth Map for 3D Craniofacial Reconstruction",
    authors: "Niankai Zhang, Junli Zhao, Fuqing Duan, Zhenkuan Pan, Zhongke Wu, Mingquan Zhou, Xianfeng Gu",
    venue: "30th ACM International Conference on Multimedia: 759–768",
    ranking: ["CCF A"],
    badge: "ACM MM 2022",
    image: "/images/publications/acm-mm-depth-map.jpg",
    doi: "https://doi.org/10.1145/3503161.3548254",
    representative: true,
  },
  {
    id: "reflectance-attention-2022",
    year: 2022,
    title: "Material Reflectance Property Estimation of Complex Objects Using an Attention Network",
    authors: "Bin Cheng, Junli Zhao, Fuqing Duan",
    venue: "IEEE VRW 2022: 632–633",
    ranking: ["CCF A"],
    doi: "https://doi.org/10.1109/VRW55335.2022.00167",
  },
  {
    id: "elastica-skull-2022",
    year: 2022,
    title: "颅骨点云曲面重建的Euler's Elastica模型",
    authors: "牛慧勤, 潘振宽, 赵俊莉, 周明全",
    venue: "计算机辅助设计与图形学学报, 34(10)",
    doi: "https://doi.org/10.3724/SP.J.1089.2022.19726",
  },
  {
    id: "skull-gender-fc-2022",
    year: 2022,
    title: "基于全卷积自加权分类器的三维颅骨性别鉴定",
    authors: "张念凯, 乔学军, 热孜万古丽·夏米西丁, 赵俊莉",
    venue: "青岛大学学报(自然科学版), 35(3)",
  },
  {
    id: "skull-repair-2022",
    year: 2022,
    title: "基于径向曲线与支持向量回归的颅骨修复方法",
    authors: "陈仲晗, 赵俊莉, 黄瑞坤",
    venue: "计算机工程, 48(1): 305–311",
  },
  {
    id: "geodesic-regression-2021",
    year: 2021,
    title: "基于测地回归模型的颅面复原",
    authors: "陈仲晗, 赵俊莉, 于晗, 潘振宽, 贾彬, 李劲华",
    venue: "计算机辅助设计与图形学学报, 33(3)",
    doi: "https://doi.org/10.3724/SP.J.1089.2021.18320",
  },
  {
    id: "craniofacial-similarity-review-2021",
    year: 2021,
    title: "颅面相似性度量与评价",
    authors: "赵俊莉, 周明全, 王曦, 张念凯, 耿国华, 税午阳, 张娟",
    venue: "西北大学学报(自然科学版), 51(5)",
    doi: "https://doi.org/10.16152/j.cnki.xdxbzr.2021-05-002",
  },
  {
    id: "skull-ethnic-qb-2021",
    year: 2021,
    title: "Skull ethnic classification by combining skull auxiliary image with deep learning",
    authors: "Huijie Sun, Junli Zhao, Chengyuan Wang, Yi Li, Niankai Zhang, Mingquan Zhou",
    venue: "Quantitative Biology, 2021",
    doi: "https://doi.org/10.15302/J-QB-021-0269",
  },
  {
    id: "gan-superresolution-2021",
    year: 2021,
    title: "基于生成式对抗网络的图像超分辨率重建算法",
    authors: "姜玉宁, 李劲华, 赵俊莉",
    venue: "计算机工程, 47(3)",
  },
  {
    id: "medical-fusion-dl-2021",
    year: 2021,
    title: "Medical image fusion method by deep learning",
    authors: "Yi Li, Junli Zhao, Zhihan Lv, Jinhua Li",
    venue: "International Journal of Cognitive Computing in Engineering, 2: 21–29",
    doi: "https://doi.org/10.1016/j.ijcce.2020.12.004",
  },
  {
    id: "parallel-gan-expression-2021",
    year: 2021,
    title: "基于并行GAN的有遮挡动态表情识别",
    authors: "杨鲁月, 张树美, 赵俊莉",
    venue: "计算机工程与应用, 57(24)",
    doi: "https://doi.org/10.3778/j.issn.1002-8331.2007-0130",
  },
  {
    id: "hf-ggr-2021",
    year: 2021,
    title: "Craniofacial Reconstruction Based on Heat Flow Geodesic Grid Regression (HF-GGR) Model",
    authors: "Bin Jia, Junli Zhao, Shiqing Xin, Fuqing Duan, Zhenkuan Pan, Zhongke Wu, Jinhua Li, Mingquan Zhou",
    venue: "Computers & Graphics, 97: 258–267",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1016/j.cag.2021.04.029",
  },
  {
    id: "ethnic-classification-2021",
    year: 2021,
    title: "结合颅骨形态特征与神经网络的民族判别",
    authors: "孙慧杰, 赵俊莉, 郑鑫, 热孜万古丽·夏米西丁, 李奕, 周明全",
    venue: "北京航空航天大学学报, 47(3): 641–649",
  },
  {
    id: "radial-curve-sr-2020",
    year: 2020,
    title: "3D Face Model Super-Resolution Based on Radial Curve Estimation",
    authors: "Fan Zhang, Junli Zhao, Liang Wang, Fuqing Duan",
    venue: "Applied Sciences, 10(3): 1047",
    doi: "https://doi.org/10.3390/app10031047",
  },
  {
    id: "radial-curve-statistical-2020",
    year: 2020,
    title: "颅面的径向曲线统计复原模型",
    authors: "王琳, 赵俊莉, 黄瑞坤, 李淑娴, 李守哲",
    venue: "光学精密工程, 28(12)",
  },
  {
    id: "cnn-ensemble-expression-2020",
    year: 2020,
    title: "基于CNN集成的面部表情识别",
    authors: "陆嘉慧, 张树美, 赵俊莉",
    venue: "青岛大学学报(工程技术版), 35(2): 24–29",
  },
  {
    id: "srcgan-2020",
    year: 2020,
    title: "基于SRCGAN的超分辨率图像重建算法研究",
    authors: "毕玉萍, 李劲华, 赵俊莉",
    venue: "计算机应用与软件, 37(7)",
  },
  {
    id: "dl-expression-2020",
    year: 2020,
    title: "基于深度学习的面部表情识别研究",
    authors: "陆嘉慧, 张树美, 赵俊莉",
    venue: "计算机应用研究, 37(4)",
  },
  {
    id: "occluded-face-review-2020",
    year: 2020,
    title: "有遮挡人脸识别方法综述",
    authors: "董艳花, 张树美, 赵俊莉",
    venue: "计算机工程与应用, 56(9)",
    doi: "https://doi.org/10.3778/j.issn.1002-8331.2001-0029",
  },
  {
    id: "geodesics-survey-2019",
    year: 2019,
    title: "A Survey on 3D Face Recognition based on Geodesics",
    authors: "Junli Zhao, Zhenkuan Pan, Fuqing Duan, Zhihan Lv, Jinhua Li, Qiang Zhou, Xiangang Shang, Jie Sun, Pingping Wang",
    venue: "Journal of Information Hiding and Multimedia Signal Processing, 10(2)",
  },
  {
    id: "craniofacial-restoration-survey-2019",
    year: 2019,
    title: "颅面复原方法综述",
    authors: "王琳, 赵俊莉, 段福庆, 周明全",
    venue: "计算机工程, 45(12): 8–18",
  },
  {
    id: "parallel-cnn-expression-2019",
    year: 2019,
    title: "构建并行卷积神经网络的表情识别算法",
    authors: "徐琳琳, 张树美, 赵俊莉",
    venue: "中国图象图形学报, 24(2)",
  },
  {
    id: "mtap-fusion-2019",
    year: 2019,
    title: "Improving performance of medical image fusion using histogram, dictionary learning and sparse representation",
    authors: "Yi Li, Zhihan Lv, Junli Zhao, Zhenkuan Pan",
    venue: "Multimedia Tools and Applications",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1007/s11042-019-08027-9",
  },
  {
    id: "skull-registration-2019",
    year: 2019,
    title: "Automatic and Robust Skull Registration Based on Discrete Uniformization",
    authors: "Junli Zhao, Xin Qi, Chengfeng Wen, Na Lei, Xianfeng Gu",
    venue: "IEEE/CVF International Conference on Computer Vision (ICCV): 431–440",
    ranking: ["CCF A"],
    badge: "ICCV 2019",
    image: "/images/publications/iccv-skull-registration.jpg",
    pdf: "https://openaccess.thecvf.com/content_ICCV_2019/papers/Zhao_Automatic_and_Robust_Skull_Registration_Based_on_Discrete_Uniformization_ICCV_2019_paper.pdf",
    doi: "https://doi.org/10.1109/ICCV.2019.00052",
    featured: true,
    representative: true,
  },
  {
    id: "radial-curves-2019",
    year: 2019,
    title: "Automatic Craniofacial Registration Based on Radial Curves",
    authors: "Ruikun Huang, Junli Zhao, Fuqing Duan, Xin Li, Celong Liu, Xiaodan Deng, Zhenkuan Pan, Zhongke Wu, Mingquan Zhou",
    venue: "Computers & Graphics, 82: 264–274",
    ranking: ["CCF C"],
    doi: "https://doi.org/10.1016/j.cag.2019.05.026",
  },
  {
    id: "frechet-geodesics-2018",
    year: 2018,
    title: "3D Face Similarity Measure by Fréchet Distances of Geodesics",
    authors: "Junli Zhao, Zhong-Ke Wu, Zhenkuan Pan, Fu-Qing Duan, Jin-Hua Li, Zhi-Han Lv, Kang Wang, Yu-Cong Chen",
    venue: "Journal of Computer Science and Technology, 33(1): 207–222",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1007/s11390-018-1814-7",
  },
  {
    id: "conformal-face-recognition-2018",
    year: 2018,
    title: "3D Face Recognition Based on Local Conformal Parameterization and Iso-Geodesic Stripes Analysis",
    authors: "Chenlei Lv, Junli Zhao",
    venue: "Mathematical Problems in Engineering, 2018: 4707954",
    ranking: ["SCI"],
    doi: "https://doi.org/10.1155/2018/4707954",
  },
  {
    id: "cnn-feature-graph-2017",
    year: 2017,
    title: "CNN Expression Recognition Based on Feature Graph",
    authors: "Lin-Lin Xu, Shu-Mei Zhang, Fu-Xing Wang, Jun-Li Zhao",
    venue: "2017 IEEE ACM Cloud and Autonomic Computing Conference (CAC)",
    doi: "https://doi.org/10.1109/CAC.2017.8243428",
  },
  {
    id: "shape-space-2015",
    year: 2015,
    title: "形状空间下的3D面貌相似性比较",
    authors: "赵俊莉, 武仲科, 刘翠婷, 段福庆, 周明全, 曹嘉谊",
    venue: "光学精密工程, 23(4)",
  },
  {
    id: "discrete-geodesic-2015",
    year: 2015,
    title: "网格模型上的离散测地线",
    authors: "赵俊莉, 辛士庆, 刘永进, 王醒策, 武仲科, 周明全, 贺英",
    venue: "中国科学: 信息科学, 45(3): 313–335",
    doi: "https://doi.org/10.1360/N112014-00018",
  },
  {
    id: "geodesic-evaluation-2014",
    year: 2014,
    title: "Craniofacial Reconstruction Evaluation by Geodesic Network",
    authors: "Junli Zhao, Cuiting Liu, Zhongke Wu, Fuqing Duan, Kang Wang, Taorui Jia, Quansheng Liu",
    venue: "Computational and Mathematical Methods in Medicine, 2014: 943647",
    doi: "https://doi.org/10.1155/2014/943647",
  },
  {
    id: "geodesic-curvature-2014",
    year: 2014,
    title: "3D Facial Similarity Measure Based on Geodesic Network and Curvatures",
    authors: "Junli Zhao, Cuiting Liu, Zhongke Wu, Fuqing Duan, Minqi Zhang, Kang Wang, Taorui Jia",
    venue: "Mathematical Problems in Engineering, 2014: 832837",
    doi: "https://doi.org/10.1155/2014/832837",
  },
  {
    id: "diffusion-distance-2014",
    year: 2014,
    title: "A Scale-Invariant Diffusion Distance for Non-rigid Shape Analysis",
    authors: "Kang Wang, Zhongke Wu, Taorui Jia, Sajid Ali, Junli Zhao, Guoliang Yang, Mingquan Zhou",
    venue: "2014 International Conference on Virtual Reality and Visualization (ICVRV)",
    doi: "https://doi.org/10.1109/ICVRV.2014.63",
  },
  {
    id: "heat-kernel-2014",
    year: 2014,
    title: "Scale-Invariant Heat Kernel Mapping",
    authors: "Kang Wang, Zhongke Wu, Pengfei Xu, Junli Zhao, Taorui Jia, Wuyang Shui, Sajid Ali, Mingquan Zhou",
    venue: "2014 International Conference on Cyberworlds (CW)",
    doi: "https://doi.org/10.1109/CW.2014.24",
  },
  {
    id: "isometric-matching-2014",
    year: 2014,
    title: "Isometric Shape Matching Based on the Geodesic Structure and Minimum Cost Flow",
    authors: "Taorui Jia, Kang Wang, Zhongke Wu, Junli Zhao, Pengfei Xu, Cuiting Liu, Mingquan Zhou",
    venue: "2014 International Conference on Cyberworlds (CW)",
    doi: "https://doi.org/10.1109/CW.2014.25",
  },
  {
    id: "parameterization-registration-2014",
    year: 2014,
    title: "基于参数化的三维颅面配准",
    authors: "乔学军, 赵俊莉, 鲁健庆, 谢文魁",
    venue: "计算机应用, 34(12): 3589–3592",
    doi: "https://doi.org/10.11772/j.issn.1001-9081.2014.12.3589",
  },
];

export const publicationSummary = {
  total: publications.length,
  note: "全部论文集中在本页，按年份排列；条目信息均依据论文原文核对，链接仅在确认真实来源时显示。",
};

export const featuredPublications = publications.filter((item) => item.featured);

export const representativePublications = publications.filter((item) => item.representative);
