export type Publication = {
  id: string;
  year: number;
  title: string;
  authors: string;
  venue: string;
  ranking?: string[];
  doi?: string;
  featured?: boolean;
};

export const publications: Publication[] = [
  {
    id: "omnisketch-2026",
    year: 2026,
    title: "OmniSketch: Sketch-Guided Text-to-3D Generation With High-Fidelity Geometry and Texture",
    authors: "Xinbin Sun, Zhentong Xu, Guodong Wang, Fuqing Duan, Junli Zhao, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE Computer Graphics and Applications, 46(3): 68–81",
    featured: true,
  },
  {
    id: "cranial-open-surface-2025",
    year: 2025,
    title: "Model-Guided 3D Cranial Open Surface Reconstruction Based on Euler's Elastica and Optimal Transport",
    authors: "Lijun Zhu, Junli Zhao, Pengbo Zhou, Guodong Wang, Huiqin Niu, Zhenkuan Pan",
    venue: "ICXR 2025: 116–132",
  },
  {
    id: "cpess-2025",
    year: 2025,
    title: "CPESS: Lightweight Hemiplegia Recognition Based on Video Pose Estimation and Sparse Spatiotemporal Graph Convolutional Networks",
    authors: "Yaoliang Wang, Xuesong Wang, Chong Chen, Xin He, Baodong Wang, Junli Zhao, Jianjun Sun, Lei Peng, Shuzhe Yang, Qiang Jian",
    venue: "ICXR 2025: 442–453",
  },
  {
    id: "weighted-poisson-2025",
    year: 2025,
    title: "Weighted Poisson-disk Resampling on Large-Scale Point Clouds",
    authors: "Xianhe Jiao, Chenlei Lv, Junli Zhao, Ran Yi, Yu-Hui Wen, Zhenkuan Pan, Zhongke Wu, Yong-Jin Liu",
    venue: "Proceedings of the AAAI Conference on Artificial Intelligence, 39(4): 4084–4092",
    ranking: ["CCF A"],
    featured: true,
  },
  {
    id: "skull-to-face-2025",
    year: 2025,
    title: "Skull-to-Face: Anatomy-Guided 3D Facial Reconstruction and Editing",
    authors: "Yongqing Liang, Congyi Zhang, Junli Zhao, Wenping Wang, Xin Li",
    venue: "IEEE Transactions on Visualization and Computer Graphics, 31(9): 6425–6436",
    ranking: ["SCI 1区", "CCF A"],
    featured: true,
  },
  {
    id: "sketch123-2025",
    year: 2025,
    title: "Sketch123: Multi-spectral Channel Cross Attention for Sketch-based 3D Generation via Diffusion Models",
    authors: "Zhentong Xu, Long Zeng, Junli Zhao, Baodong Wang, Zhenkuan Pan, Yong-Jin Liu",
    venue: "Computer-Aided Design, 185: 103896",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1016/j.cad.2025.103896",
  },
  {
    id: "craniofacial-superimposition-2025",
    year: 2025,
    title: "Geometric Feature-Driven Metric Learning for 3D Craniofacial Superimposition",
    authors: "Qingdong Long, Junli Zhao, Fuqing Duan, Chengyuan Wang, Xuesong Wang, Lijie Geng, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE ICASSP 2025: 1–5",
    ranking: ["CCF B"],
  },
  {
    id: "gausurfaceavatar-2025",
    year: 2025,
    title: "GauSurfaceAvatar: A Realistic Human Head Model with Variable Texture Based on 2D Gaussians",
    authors: "Lijie Geng, Junli Zhao, Lin Gao, Ran Yi, Fuqing Duan, Zhenkuan Pan, Yong-Jin Liu",
    venue: "IEEE ICME 2025: 1–6",
    ranking: ["CCF B"],
    doi: "https://doi.org/10.1109/ICME59968.2025.11209075",
  },
  {
    id: "4dm-lddm-2025",
    year: 2025,
    title: "4DM-LDDM: A Mesh Latent Diffusion Deformable Model for 4D Facial Generation",
    authors: "B. Wang, Z. Wang, J. Zhao, Z. Pan",
    venue: "IEEE Access, 13: 183534–183548",
    doi: "https://doi.org/10.1109/ACCESS.2025.3625413",
  },
  {
    id: "mmae-2025",
    year: 2025,
    title: "MMAE: A Universal Image Fusion Method via Mask Attention Mechanism",
    authors: "Xiangxiang Wang, Lixing Fang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Pattern Recognition, 158: 111041",
    ranking: ["SCI 1区", "CCF B"],
  },
  {
    id: "vitau-2025",
    year: 2025,
    title: "ViTAU：基于 Vision Transformer 和面部动作单元的面瘫识别与分析",
    authors: "高嘉, 蔡文浩, 赵俊莉, 段福庆",
    venue: "工程科学学报, 47(2): 351–363",
  },
  {
    id: "msl-net-2024",
    year: 2024,
    title: "MSL-Net: Sharp Feature Detection Network for 3D Point Clouds",
    authors: "Xianhe Jiao, Chenlei Lv, Ran Yi, Junli Zhao, Zhenkuan Pan, Zhongke Wu, Yong-Jin Liu",
    venue: "IEEE Transactions on Visualization and Computer Graphics, 30(9): 6433–6446",
    ranking: ["SCI 1区", "CCF A"],
    featured: true,
  },
  {
    id: "siamese-cycle-2024",
    year: 2024,
    title: "Intrinsic Morphological Relationship Guided 3D Craniofacial Reconstruction Using Siamese Cycle Attention GAN",
    authors: "Junli Zhao, Chengyuan Wang, Yu-Hui Wen, Fuqing Duan, Ran Yi, Yong-Jin Liu, Qingdong Long, Zhenkuan Pan, Xianfeng Gu",
    venue: "SIGGRAPH Asia 2024 Technical Communications",
    featured: true,
  },
  {
    id: "mfdan-2024",
    year: 2024,
    title: "MFDAN: Multi-level Flow-Driven Attention Network for Micro-Expression Recognition",
    authors: "Wenhao Cai, Junli Zhao, Ran Yi, Minjing Yu, Fuqing Duan, Zhenkuan Pan, Yong-Jin Liu",
    venue: "IEEE Transactions on Circuits and Systems for Video Technology, 34(12): 12823–12836",
    ranking: ["SCI 1区", "CCF B"],
    doi: "https://doi.org/10.1109/TCSVT.2024.3437481",
  },
  {
    id: "skeletonformer-2024",
    year: 2024,
    title: "SkeletonFormer: Point Cloud Completion with Dynamic Selective Skeleton Points",
    authors: "Beiqi Liu, Fuqing Duan, Junli Zhao",
    venue: "ICMR 2024: 897–905",
    ranking: ["CCF B"],
  },
  {
    id: "uud-fusion-2024",
    year: 2024,
    title: "UUD-Fusion: An Unsupervised Universal Image Fusion Approach via Generative Diffusion Model",
    authors: "Xiangxiang Wang, Lixing Fang, Junli Zhao, Zhenkuan Pan, Hui Li, Yi Li",
    venue: "Computer Vision and Image Understanding, 249: 104218",
    ranking: ["CCF B"],
  },
  {
    id: "mattrans-2024",
    year: 2024,
    title: "MatTrans: Material Reflectance Property Estimation of Complex Objects with Transformer",
    authors: "Liping Wu, Bin Cheng, Wentao Chao, Junli Zhao, Fuqing Duan",
    venue: "CVM 2024: 197–217",
    ranking: ["CCF C"],
  },
  {
    id: "identity-preserving-2024",
    year: 2024,
    title: "Identity-preserving 3D Facial Completion under Skull Constraints",
    authors: "Longtao Yu, Junli Zhao, Fuqing Duan, Chenlei Lv, Dantong Li, Zhenkuan Pan, Mingquan Zhou",
    venue: "IEEE International Joint Conference on Biometrics (IJCB): 1–10",
    ranking: ["CCF C"],
  },
  {
    id: "skull-gender-2024",
    year: 2024,
    title: "Morphology-Guided 3D Skull Gender Identification with Point-BERT",
    authors: "Baodong Wang, Shuo Wang, Junli Zhao, Tongyan Liu, Zhi Wang, Zhenkuan Pan, Mingquan Zhou",
    venue: "ICONIP 2024, Communications in Computer and Information Science 2296",
    ranking: ["CCF C"],
  },
  {
    id: "pottsnn-2024",
    year: 2024,
    title: "PottsNN: A Variational Neural Network Based on Potts Model for Image Segmentation",
    authors: "Reyan Wang, Zhenghong Zhong, Junli Zhao, Shaoqing Gong, Zhenkuan Pan, Weibo Wei",
    venue: "PRCV 2024: 142–156",
    ranking: ["CCF C"],
  },
  {
    id: "craniofacial-landmarks-2023",
    year: 2023,
    title: "Robust 3D Craniofacial Landmarks Localization by An End-to-End Regression Network",
    authors: "Xianhe Jiao, Junli Zhao, Chenlei Lv, Fuqing Duan, Zhenkuan Pan, Xin Li",
    venue: "IEEE ICME 2023: 900–905",
    ranking: ["CCF B"],
  },
  {
    id: "4d-facial-survey-2023",
    year: 2023,
    title: "4D Facial Analysis: A Survey of Datasets, Algorithms and Applications",
    authors: "Yong-Jin Liu, Baodong Wang, Lin Gao, Junli Zhao, Ran Yi, Minjing Yu, Zhenkuan Pan, Xianfeng Gu",
    venue: "Computers & Graphics, 115: 423–445",
    ranking: ["CCF C"],
  },
  {
    id: "cr-net-2023",
    year: 2023,
    title: "CR-Net: A Robust Craniofacial Registration Network by Introducing Wasserstein Distance Constraint and Geometric Attention Mechanism",
    authors: "Zhenyu Dai, Junli Zhao, Xiaodan Deng, Fuqing Duan, Dantong Li, Zhenkuan Pan, Mingquan Zhou",
    venue: "Computers & Graphics, 116: 194–205",
    ranking: ["CCF C"],
  },
  {
    id: "depth-map-craniofacial-2022",
    year: 2022,
    title: "An End-to-End Conditional Generative Adversarial Network Based on Depth Map for 3D Craniofacial Reconstruction",
    authors: "Niankai Zhang, Junli Zhao, Fuqing Duan, Zhenkuan Pan, Zhongke Wu, Mingquan Zhou, Xianfeng Gu",
    venue: "30th ACM International Conference on Multimedia: 759–768",
    ranking: ["CCF A"],
  },
  {
    id: "reflectance-attention-2022",
    year: 2022,
    title: "Material Reflectance Property Estimation of Complex Objects Using an Attention Network",
    authors: "Bin Cheng, Junli Zhao, Fuqing Duan",
    venue: "IEEE VRW 2022: 632–633",
    ranking: ["CCF A"],
  },
  {
    id: "skull-repair-2022",
    year: 2022,
    title: "基于径向曲线与支持向量回归的颅骨修复方法",
    authors: "陈仲晗, 赵俊莉, 黄瑞坤",
    venue: "计算机工程, 48(1): 305–311",
  },
  {
    id: "hf-ggr-2021",
    year: 2021,
    title: "Craniofacial Reconstruction Based on Heat Flow Geodesic Grid Regression (HF-GGR) Model",
    authors: "Bin Jia, Junli Zhao, Shiqing Xin, Fuqing Duan, Zhenkuan Pan, Zhongke Wu, Jinhua Li, Mingquan Zhou",
    venue: "Computers & Graphics, 97: 258–267",
    ranking: ["CCF C"],
  },
  {
    id: "ethnic-classification-2021",
    year: 2021,
    title: "结合颅骨形态特征与神经网络的民族判别",
    authors: "孙慧杰, 赵俊莉, 郑鑫, 热孜万古丽·夏米西丁, 李奕, 周明全",
    venue: "北京航空航天大学学报, 47(3): 641–649",
  },
  {
    id: "skull-spca-2020",
    year: 2020,
    title: "Skull Similarity Comparison Based on SPCA",
    authors: "Xin Zheng, Junli Zhao, Zhihan Lv, Fuqing Duan, Zhenkuan Pan",
    venue: "Multimedia Tools and Applications: 1–24",
    ranking: ["CCF C"],
  },
  {
    id: "skull-registration-2019",
    year: 2019,
    title: "Automatic and Robust Skull Registration Based on Discrete Uniformization",
    authors: "Junli Zhao, Xin Qi, Chengfeng Wen, Na Lei, Xianfeng Gu",
    venue: "IEEE/CVF International Conference on Computer Vision: 431–440",
    ranking: ["CCF A"],
    featured: true,
  },
  {
    id: "radial-curves-2019",
    year: 2019,
    title: "Automatic Craniofacial Registration Based on Radial Curves",
    authors: "Ruikun Huang, Junli Zhao, Fuqing Duan, Xin Li, Celong Liu, Xiaodan Deng, Zhenkuan Pan, Zhongke Wu, Mingquan Zhou",
    venue: "Computers & Graphics, 82: 264–274",
    ranking: ["CCF C"],
  },
  {
    id: "frechet-geodesics-2018",
    year: 2018,
    title: "3D Face Similarity Measure by Fréchet Distances of Geodesics",
    authors: "Junli Zhao, Zhong-ke Wu, Zhenkuan Pan, Fu-Qing Duan, Jin-Hua Li, Zhi-Han Lv, Kang Wang, Yu-Cong Chen",
    venue: "Journal of Computer Science and Technology, 33: 207–222",
    ranking: ["CCF B"],
  },
  {
    id: "conformal-face-recognition-2018",
    year: 2018,
    title: "3D Face Recognition Based on Local Conformal Parameterization and Iso-Geodesic Stripes Analysis",
    authors: "Chenlei Lv, Junli Zhao",
    venue: "Mathematical Problems in Engineering",
    ranking: ["SCI"],
  },
  {
    id: "discrete-geodesic-2015",
    year: 2015,
    title: "网格模型上的离散测地线",
    authors: "赵俊莉, 辛士庆, 刘永进, 王醒策, 武仲科, 周明全, 贺英",
    venue: "中国科学：信息科学, 3: 002",
  },
];

export const publicationSummary = {
  totalInCv: 68,
  note: "本页首版展示个人简历中的精选论文，完整目录可继续通过结构化数据追加。",
};

export const featuredPublications = publications.filter((item) => item.featured);

